sudo: required
services:
  - docker

before_install:
  - docker build -t nikhil15a/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nikhil15a/react-test npm test

after_success:
  - docker build -t nikhil15a/multi-client ./client
  - docker build -t nikhil15a/multi-nginx ./nginx
  - docker build -t nikhil15a/multi-server ./server
  - docker build -t nikhil15a/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nikhil15a/multi-client
  - docker push nikhil15a/multi-nginx
  - docker push nikhil15a/multi-server
  - docker push nikhil15a/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-container
  env: MultiContainer-env
  bucket_name: elasticbeanstalk-us-east-2-031033820552
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
